### ISSUE TITLE
Too Many Requests for jettech/kube-webhook-certgen:v1.5.2

### ISSUE THREAD

**Issue by dex4er** [estahn/charts#107]
I've got an error

```
Failed to pull image "jettech/kube-webhook-certgen:v1.5.2": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/jettech/kube-webhook-certgen:v1.5.2": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/jettech/kube-webhook-certgen/manifests/sha256:aef46427991165d16db3b9323472855425e7d3d737d539ee19d43305925b5827: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

![image](https://user-images.githubusercontent.com/174367/210265343-2515a0fc-e99b-47a5-88d9-7328c1c96eba.png)

**Comment by dex4er** [comment]
I think it fixed my problem and additionally it fixed another ugly bug https://github.com/kubernetes/ingress-nginx/issues/7418

```yaml
patch:
  ## https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L659
  image:
    repository: registry.k8s.io/ingress-nginx/kube-webhook-certgen
    tag: v20220916-gd32f8c343
  priorityClassName: system-cluster-critical
```
